export const constants = {
  API_SERVER: "http://localhost:8081",
  SUCCESS_STATE: "SUCCESS",
  ERROR_STATE: "ERROR",
  DEFAULT_CUSTOMER: {
    id: 0,
    firstName: "",
    gender: "",
    mobile: 0,
    lastName: "",
    email: "",
    languages: [],
    rating:0.0,
    state: "",
    message: "",
    enabled: false,
    professional: false,
    contact: {
      customerId: 0,
      email: "",
      mobile: 0,
      addressLine1: "",
      addressLine2: "",
      addressLine3: "",
      city: "",
      pincode: 0,
      state: "",
      message: ""
    },
  },
  DEFAULT_LISTING: {
    id: 0,
    charges: 0,
    chargesType: "",
    professionalEmail: "",
    professionalId: 0,
    subCategoryName: "",
    state: "",
    message: "",
    experience: 0,
    subCategory: {
      id:0,
      subCategoryName: "",
      categoryName: ""
    },
    location: "",
    professional: {
      id: 0,
      firstName: "",
      lastName: "",
      languages: [],
      state: "",
      message: "",
      profilePhoto: {
        id: 0,
        customerId: 0,
        picByte: 0,
        state: "",
        message: ""
      },
      enabled: false,
      professional: false
    },
  },
  DEFAULT_CONTACT_DETAIL: {
    customerId: 0,
    email: "",
    mobile: 0,
    addressLine1: "",
    addressLine2: "",
    addressLine3: "",
    city: "",
    pincode: 0,
    state: "",
    message: ""
  },
  TIMESLOTS: [
    "7:00AM", "7:30AM",
    "8:00AM", "8:30AM",
    "9:00AM", "9:30AM",
    "10:00AM", "10:30AM",
    "11:00AM", "11:30AM",
    "12:00PM", "12:30PM",
    "1:00PM", "1:30PM",
    "2:00PM", "2:30PM",
    "3:00PM", "3:30PM",
    "4:00PM", "4:30PM",
    "5:00PM", "5:30PM",
    "6:00PM", "6:30PM",
    "7:00PM", "7:30PM",
    "8:00PM", "8:30PM",
    "9:00PM", "9:30PM",
    "10:00PM", "10:30PM",
    "11:00PM"
  ],
  ORDER_ACTION_START: "START",
  ORDER_ACTION_COMPLETE: "COMPLETE",
  ORDER_ACTION_CANCEL: "CANCEL"
};